export type Factor = { id: string; label: string; weight: number; layerKind: string };
export type SiteType = { id: string; label: string; summary: string; factors: Factor[]; constraints: string[] };
const factor = (id: string, label: string, weight: number, layerKind: string): Factor => ({ id, label, weight, layerKind });
const common = { demand: 'Population demand', access: 'Road and transit access', competition: 'Competitor gap', zoning: 'Land-use fit', risk: 'Environmental safety', utility: 'Utility readiness', footfall: 'Footfall proxy', parcel: 'Parcel suitability', gap: 'Coverage gap' };
const f = (id: keyof typeof common, weight: number, layerKind = 'demographics') => factor(id, common[id], weight, layerKind);
export const siteTypes: SiteType[] = [
 {id:'fmcg_retail',label:'FMCG / Retail Store',summary:'Household demand, visibility, access, and manageable competition.',factors:[f('demand',.30),f('access',.20,'transport'),f('competition',.20,'poi'),f('zoning',.15,'land_use'),f('risk',.15,'environmental_risk')],constraints:['commercial zoning','flood-risk policy']},
 {id:'convenience_store',label:'Convenience Store',summary:'Dense residents, walkability, and repeat daily demand.',factors:[f('demand',.30),f('footfall',.25,'transport'),f('competition',.20,'poi'),f('zoning',.15,'land_use'),f('risk',.10,'environmental_risk')],constraints:['commercial or mixed-use zoning']},
 {id:'hospital_clinic',label:'Hospital / Clinic',summary:'Population need, emergency access, parcel fit, and low risk.',factors:[f('demand',.25),f('access',.25,'transport'),f('parcel',.20,'land_use'),f('risk',.20,'environmental_risk'),f('competition',.10,'poi')],constraints:['healthcare permission','emergency access']},
 {id:'ev_charging',label:'EV Charging Station',summary:'Traffic, dwell-time POIs, grid readiness, and a coverage gap.',factors:[f('access',.25,'transport'),f('utility',.25,'utilities'),f('gap',.20),f('footfall',.15,'transport'),f('risk',.15,'environmental_risk')],constraints:['safe vehicle access','verified electrical capacity']},
 {id:'fuel_station',label:'Petrol / Fuel Station',summary:'Vehicle flow, safe ingress/egress, parcel fit, and safety.',factors:[f('access',.35,'transport'),f('parcel',.25,'land_use'),f('demand',.15),f('competition',.15,'poi'),f('risk',.10,'environmental_risk')],constraints:['fuel-station zoning and setbacks','safe ingress and egress']},
 {id:'warehouse_logistics',label:'Warehouse / Logistics Hub',summary:'Highway connectivity, industrial land, parcel size, and low disruption risk.',factors:[f('access',.35,'transport'),f('parcel',.25,'land_use'),f('zoning',.20,'land_use'),f('risk',.10,'environmental_risk'),f('demand',.10)],constraints:['industrial/logistics zoning','minimum parcel area']},
 {id:'restaurant_cafe',label:'Restaurant / Café',summary:'Footfall, complementary activity, visibility, and local demand.',factors:[f('footfall',.30,'transport'),f('demand',.25),f('competition',.20,'poi'),f('access',.15,'transport'),f('zoning',.10,'land_use')],constraints:['food-service-permitted zoning']},
 {id:'pharmacy',label:'Pharmacy',summary:'Residential demand, clinic proximity, access, and a competition gap.',factors:[f('demand',.30),f('access',.20,'transport'),f('competition',.20,'poi'),f('footfall',.15,'transport'),f('zoning',.15,'land_use')],constraints:['commercial or mixed-use zoning']},
 {id:'bank_atm',label:'Bank / ATM',summary:'Commercial footfall, safety, access, and financial-service gaps.',factors:[f('footfall',.30,'transport'),f('demand',.20),f('gap',.20),f('access',.15,'transport'),f('zoning',.15,'land_use')],constraints:['secure, accessible commercial location']},
 {id:'telecom_tower',label:'Telecom Tower',summary:'Coverage gap, served population, site access, and regulation.',factors:[f('gap',.35),f('demand',.25),f('access',.15,'transport'),f('parcel',.15,'land_use'),f('risk',.10,'environmental_risk')],constraints:['telecom, aviation, heritage, and setback review']},
 {id:'solar_installation',label:'Solar Installation',summary:'Land/roof suitability, grid readiness, low risk, and access.',factors:[f('parcel',.30,'land_use'),f('utility',.25,'utilities'),f('risk',.20,'environmental_risk'),f('access',.15,'transport'),f('zoning',.10,'land_use')],constraints:['land-use permission','protected-area and grid review']}
];
